version: '3.8'
name: attendance

services:
  codebase-1:
    container_name: attendance-1
    image: attendance-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: quangkhanh
      DB_PASS: 2882004
      MAIL_USERNAME: khanhquang2882004@gmail.com
      MAIL_PASSWORD: 2882004
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis
    networks:
      - attendance-network

  codebase-2:
    container_name: attendance-2
    image: attendance-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: quangkhanh
      DB_PASS: 2882004
      MAIL_USERNAME: khanhquang2882004@gmail.com
      MAIL_PASSWORD: 2882004
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8001:8000
    depends_on:
      - mysql
      - redis
    networks:
      - attendance-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    networks:
      - attendance-network
    depends_on:
      - codebase-1
      - codebase-2

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot \
      --email 22520674@gm.uit.edu.vn --agree-tos --no-eff-email \
      -d api.attendance.kwork.live"

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "while :; do certbot renew --webroot --webroot-path=/var/www/certbot && docker exec nginx nginx -s reload; sleep 12h; done"

  mysql:
    image: mysql:5.7.40
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=quangkhanh
      - MYSQL_PASSWORD=2882004
      - MYSQL_ROOT_PASSWORD=quangkhanh
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - attendance-network

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge
