version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  e2e-tests:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    environment:
      DB_HOST:
      DB_PORT:
      DB_USER:
      DB_PASS:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      SPRING_PROFILES_ACTIVE: test
    command: mvn clean verify -Dspring.profiles.active=test
    depends_on:
      redis:
        condition: service_healthy
