global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'attendance-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          application: 'Attendance Service Application'


