name: E2E Tests

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Run E2E Tests
        run: mvn clean verify -Dspring.profiles.active=test
