name: Generate and Store SSH Key

on:
  workflow_dispatch:

jobs:
  generate-and-store-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          echo "SSH public key:"
          cat ~/.ssh/id_rsa.pub

      - name: Fetch Public Key
        id: get_public_key
        run: |
          PUBLIC_KEY_RESPONSE=$( curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
           # Debug: Print the full response
          echo "Response: $PUBLIC_KEY_RESPONSE"
          PUBLIC_KEY=$(echo "$PUBLIC_KEY_RESPONSE" | jq -r .key)
          KEY_ID=$(echo "$PUBLIC_KEY_RESPONSE" | jq -r .key_id)
          echo "PUBLIC_KEY=$PUBLIC_KEY" >> $GITHUB_ENV
          echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV
        env:
          TOKEN: ${{ secrets.MY_PAT }}

      - name: Encrypt Private Key
        env:
          PUBLIC_KEY: ${{ env.PUBLIC_KEY }}
        run: |
          echo "$PUBLIC_KEY" | base64 -d > public_key.pem
          ls -l public_key.pem
          cat public_key.pem
          ENCRYPTED_PRIVATE_KEY=$(cat ~/.ssh/id_rsa | openssl rsautl -encrypt -pubin -inkey public_key.pem | base64)
          echo "ENCRYPTED_PRIVATE_KEY=$ENCRYPTED_PRIVATE_KEY" >> $GITHUB_ENV
          echo "Encrypted_Private_Key: $ENCRYPTED_PRIVATE_KEY"

      - name: Save Private Key to GitHub Secret
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/SSH_PRIVATE_KEY \
            -d "{\"encrypted_value\":\"${{ env.ENCRYPTED_PRIVATE_KEY }}\", \"key_id\":\"${{ env.KEY_ID }}\"}"
